### ISSUE TITLE
console.time and .timeEnd disallowed

### ISSUE THREAD

**Issue by JirkaDellOro** [palantir/eclipse-tslint#14]
```javascript
console.time("construct");
....
console.timeEnd("construct");
```
produces two warnings stating "function invocation disallowed"

**Comment by gscshoyru** [comment]
You probably want to be filling these against https://github.com/palantir/tslint itself, not against the eclipse plugin.  

You're likely using the example tslint.json, which has the no-console rule with those functions disallowed. If you remove those options, tslint will stop checking those.

**Comment by JirkaDellOro** [comment]
Indeed, that was the case... missed it.
